### ISSUE TITLE
cookbook doesn't work on Amazon 2014.03

### ISSUE THREAD

**Issue by ruixia** [sous-chefs/mysql#229]
I am using Packer to build an Amazon AMI that installs mysql by mysql cookbook (version 5.5.1).  It fails due to yum repo conflicts.

Linux version

```
[ec2-user@ip-xxxxxxxxx ~]$ cat /etc/system-release
Amazon Linux AMI release 2014.03
[ec2-user@ip-xxxxxxxxx ~]$ cat /etc/system-release-cpe
cpe:/o:amazon:linux:2014.03:ga
```

Chef messages

```
    amazon-ebs: * execute[yum-makecache-mysql55-community] action run
    amazon-ebs: - execute yum -q makecache --disablerepo=* --enablerepo=mysql55-community
    amazon-ebs: * ruby_block[yum-cache-reload-mysql55-community] action create
    amazon-ebs: - execute the ruby block yum-cache-reload-mysql55-community
    amazon-ebs: * execute[yum-makecache-mysql55-community] action nothing (skipped due to action :nothing)
    amazon-ebs: * ruby_block[yum-cache-reload-mysql55-community] action nothing (skipped due to action :nothing)
    amazon-ebs:
    amazon-ebs: - evaluate block and run any associated actions
    amazon-ebs: * package[mysql-community-server] action install
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs: Error executing action `install` on resource 'package[mysql-community-server]'
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: Chef::Exceptions::Exec
    amazon-ebs: ----------------------
    amazon-ebs: returned 1, expected 0
    amazon-ebs:
    amazon-ebs: Resource Declaration:
    amazon-ebs: ---------------------
    amazon-ebs: # In /tmp/packer-chef-solo/cookbooks-0/mysql/libraries/provider_mysql_service_rhel.rb
    amazon-ebs:
    amazon-ebs: 32:           package new_resource.parsed_package_name do
    amazon-ebs: 33:             action new_resource.parsed_package_action
    amazon-ebs: 34:             version new_resource.parsed_package_version
    amazon-ebs: 35:           end
    amazon-ebs: 36:
    amazon-ebs:
    amazon-ebs: Compiled Resource:
    amazon-ebs: ------------------
    amazon-ebs: # Declared in /tmp/packer-chef-solo/cookbooks-0/mysql/libraries/provider_mysql_service_rhel.rb:32:in `block in <class:Rhel>'
    amazon-ebs:
    amazon-ebs: package("mysql-community-server") do
    amazon-ebs: action [:install]
    amazon-ebs: retries 0
    amazon-ebs: retry_delay 2
    amazon-ebs: guard_interpreter :default
    amazon-ebs: package_name "mysql-community-server"
    amazon-ebs: version "5.5.39-5.el6"
    amazon-ebs: timeout 900
    amazon-ebs: cookbook_name :mysql
    amazon-ebs: end
    amazon-ebs:
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs: Error executing action `create` on resource 'mysql_service[default]'
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: Chef::Exceptions::Exec
    amazon-ebs: ----------------------
    amazon-ebs: package[mysql-community-server] (/tmp/packer-chef-solo/cookbooks-0/mysql/libraries/provider_mysql_service_rhel.rb line 32) had an error: Chef::Exceptions::Exec:  returned 1, expected 0
    amazon-ebs:
    amazon-ebs: Resource Declaration:
    amazon-ebs: ---------------------
    amazon-ebs: # In /tmp/packer-chef-solo/cookbooks-0/mysql/recipes/server.rb
    amazon-ebs:
    amazon-ebs: 20: mysql_service node['mysql']['service_name'] do
    amazon-ebs: 21:   version node['mysql']['version']
    amazon-ebs: 22:   port node['mysql']['port']
    amazon-ebs: 23:   data_dir node['mysql']['data_dir']
    amazon-ebs: 24:   server_root_password node['mysql']['server_root_password']
    amazon-ebs: 25:   server_debian_password node['mysql']['server_debian_password']
    amazon-ebs: 26:   server_repl_password node['mysql']['server_repl_password']
    amazon-ebs: 27:   allow_remote_root node['mysql']['allow_remote_root']
    amazon-ebs: 28:   remove_anonymous_users node['mysql']['remove_anonymous_users']
    amazon-ebs: 29:   remove_test_database node['mysql']['remove_test_database']
    amazon-ebs: 30:   root_network_acl node['mysql']['root_network_acl']
    amazon-ebs: 31:   package_version node['mysql']['server_package_version']
    amazon-ebs: 32:   package_action node['mysql']['server_package_action']
    amazon-ebs: 33:   action :create
    amazon-ebs: 34: end
    amazon-ebs:
    amazon-ebs: Compiled Resource:
    amazon-ebs: ------------------
    amazon-ebs: # Declared in /tmp/packer-chef-solo/cookbooks-0/mysql/recipes/server.rb:20:in `from_file'
    amazon-ebs:
    amazon-ebs: mysql_service("default") do
    amazon-ebs: action [:create]
    amazon-ebs: retries 0
    amazon-ebs: retry_delay 2
    amazon-ebs: guard_interpreter :default
    amazon-ebs: cookbook_name :mysql
    amazon-ebs: recipe_name "server"
    amazon-ebs: port "3306"
    amazon-ebs: data_dir "/var/lib/mysql"
    amazon-ebs: server_root_password "ilikerandompasswords"
    amazon-ebs: server_debian_password "gnuslashlinux4ev4r"
    amazon-ebs: remove_anonymous_users true
    amazon-ebs: remove_test_database true
    amazon-ebs: package_action "install"
    amazon-ebs: end
    amazon-ebs:
    amazon-ebs:
    amazon-ebs: Running handlers:
    amazon-ebs: [2014-09-05T18:52:52+00:00] ERROR: Running exception handlers
    amazon-ebs: Running handlers complete
    amazon-ebs: [2014-09-05T18:52:52+00:00] ERROR: Exception handlers complete
    amazon-ebs: [2014-09-05T18:52:52+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    amazon-ebs: Chef Client failed. 36 resources updated in 104.432105283 seconds
    amazon-ebs: [2014-09-05T18:52:52+00:00] ERROR: mysql_service[default] (mysql::server line 20) had an error: Chef::Exceptions::Exec: package[mysql-community-server] (/tmp/packer-chef-solo/cookbooks-0/mysql/libraries/provider_mysql_service_rhel.rb line 32) had an error: Chef::Exceptions::Exec:  returned 1, expected 0
    amazon-ebs: [2014-09-05T18:52:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

After chef-client failed, I checked yum.repo.d/

```
[ec2-user@ip-xxxxxxxxx ~]$ ls /etc/yum.repos.d/
amzn-main.repo     amzn-updates.repo  mysql55-community.repo
amzn-nosrc.repo    epel.repo
amzn-preview.repo  epel-testing.repo
```

Then I tried to install mysql-community-server manually "sudo yum install mysql-community-server". I got the following message.

```
Transaction check error:
  file /usr/lib64/mysql/libmysqlclient.so.18.0.0 from install of mysql-community-libs-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-libs-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysql from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/msql2mysql from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysql_config from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysql_find_rows from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysql_waitpid from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqlaccess from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqladmin from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqlbinlog from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqlcheck from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqldump from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqlimport from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqlshow from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqlslap from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysql.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysql_find_rows.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysql_waitpid.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqlaccess.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqladmin.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqldump.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqlshow.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqlslap.1.gz from install of mysql-community-client-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /etc/my.cnf from install of mysql-community-server-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-common-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/my_print_defaults from install of mysql-community-server-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/my_print_defaults.1.gz from install of mysql-community-server-5.5.39-5.el6.x86_64 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/msql2mysql from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysql_config from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysql_find_rows from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/bin/mysqlaccess from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysql.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysql_find_rows.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysql_waitpid.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqlaccess.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqladmin.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqldump.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqlshow.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64
  file /usr/share/man/man1/mysqlslap.1.gz from install of mysql-community-client-5.5.39-5.el6.i686 conflicts with file from package mysql55-5.5.38-1.0.amzn1.x86_64

Error Summary
-------------
```
